### ISSUE TITLE
testnet初级阶段需要实现的经济模型

### ISSUE THREAD

**Issue by blackpainter** [QOSGroup/qos#102]
最小化的经济模型实现

- [x] 为validator初始化token，两种选择
* 用水管实现（需要实现self delegation）
* 初始化写死
- [x] createValidatorTx
- [x] Validator投票状态记录（窗口），分两个key：一个记录bits，一个count数
- [x] InactiveValidatorTx，放入pendingTimeSlice
- [x] activeValidatorTx
- [x] closeExpireInactiveValidator，即删除 ()
- [x] Validator排序逻辑，排序依据：votingpower + 窗口内投票count + active块高度（取反）
- [x] 增发逻辑：定量
- [x] 增发的token向validator分发(含voting power的计算)

**Comment by kauchy** [comment]
validator有哪些状态，最好画个状态图

**Comment by kauchy** [comment]
Validator三个排序字段是什么意思
