### ISSUE TITLE
gov模块中的一些常量可以转为参数

### ISSUE THREAD

**Issue by blackpainter** [QOSGroup/qos#212]
- [ ] proposal fail时，对deposit的burnRate，目前常量1/2
- [x] 多少比例的voting power未投票，则proposal算fail，目前常量1/3

**Comment by imuge** [comment]
`gov/params`下增加：
- `min_proposer_deposit_rate` 提议者最小抵押比例
- `burn_rate` 提议通过(`PASS`)或不通过(`REJECT`)抵押燃烧比例
