### ISSUE TITLE
gov中增加新的通胀阶段投票功能

### ISSUE THREAD

**Issue by blackpainter** [QOSGroup/qos#216]
在genesis里的通胀阶段总有用完的时候，需要通过gov实现通胀阶段的动态添加 @imuge

**Comment by imuge** [comment]
新增`ProposalTypeAddInflationPhrase`提议类型，提交参数包括：
- `EndTime` 新通胀阶段结束时间
- `TotalAmount` 通胀`QOS`量

疑问：
- 提议者需不需要限制，比如只能是`guardian`才能提
- `EndTime`需不需要限制，比如只能在最后一个通胀结束前多少天才能提

@blackpainter @TokenxyWZY

**Comment by blackpainter** [comment]
我觉得都不需要限制，在voting power由持币人掌握的情况下，他们不应希望网络瘫痪
不过我觉得应该注意程序能否容忍当前没有任何Inflation Phrase，即当前块时间大于最后的EndTime，通胀为0即可

**Comment by imuge** [comment]
功能保留，暂不支持添加QOS增发入口，可等主网上线后社区讨论是否添加
