### ISSUE TITLE
最大有效验证节点数量支持治理修改

### ISSUE THREAD

**Issue by imuge** [QOSGroup/qos#251]

**Comment by WZJ-Study** [comment]
源代码已经支持本功能, 可以通过`qoscli tx submit-proposal`发起`ParameterChange`类型的提案, 对`stake`模块的`max_validator_cnt`参数进行修改.

> `qoscli tx submit-proposal --title 'update stake:max_validator_cnt' --proposal-type ParameterChange --proposer address1qwrcew2mqal36tvxzg43e6xn2lge8ejntdu4yg --deposit 10000 --description 'update max validator count to 12345' --params stake:max_validator_cnt:12345`
