### ISSUE TITLE
经济模型review

### ISSUE THREAD

**Issue by datalj** [QOSGroup/qos#261]
QOS经济模型代码review及经济模型相关参数确认  王志永、刘元木、周莹

**Comment by blackpainter** [comment]
https://github.com/QOSGroup/qos/blob/2b642493f8f8d3f9fd43e3a6c329ae41f73bdaeb/module/gov/abci.go#L61 

gov里每一块都tally一次，对于已投票的voting power是否可以只计算一次并记在proposal里，下一块再计算新增的投票？ @imuge

**Comment by TokenxyWZY** [comment]
经济模型模块已review完毕
