### ISSUE TITLE
经济模型相关参数使用说明整理

### ISSUE THREAD

**Issue by datalj** [QOSGroup/qos#263]

**Comment by TokenxyWZY** [comment]
## 经济模型相关参数

*  以下所有参数均可在主网上线后通过社区治理投票进行修改
*  根据QOS白皮书规定,每块产生时间为3秒.主网上线后,由于网络等原因,实际出块时间预估在4-7秒内,以下所有估算依据出块的时间为5秒
*  每块的分配来源包括通胀产生的QOS和交易产生的GAS费用. 以下所有估算不包含交易产生的GAS费用

### 铸币/挖矿模块

<table>
<tr>
<th>参数名称</th>
<th>参数释义</th>
<th>测试网默认值</th>
<th>主网上线设定值</th>
<th>备注</th>
</tr>
<tbody>
<tr>
<td>inflation_phrases</td>
<td>通胀阶段配置,根据QOS白皮书规则制定.</td>
<td>
<pre lang =“json”>
[
        {  
           "end_time": "2023-01-01T00:00:00Z",
           "total_amount": "25500000000000",
           "applied_amount": "0"
          }, 
          {  
           "end_time": "2027-01-01T00:00:00Z",
           "total_amount": "12750000000000",
            "applied_amount": "0"
          }, 
          {  
          "end_time": "2031-01-01T00:00:00Z",
          "total_amount": "6375000000000",
          "applied_amount": "0"
          }, 
          {  
            "end_time": "2035-01-01T00:00:00Z",
            "total_amount": "3185000000000",
            "applied_amount": "0"
          }  
 ] 
</pre>
</td>
<td>
<pre lang =“json”>
[
        {
          "end_time": "2023-10-20T00:00:00Z",
          "total_amount": "25500000000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2027-10-20T00:00:00Z",
          "total_amount": "12750000000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2031-10-20T00:00:00Z",
          "total_amount": "6375000000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2035-10-20T00:00:00Z",
          "total_amount": "3187500000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2039-10-20T00:00:00Z",
          "total_amount": "1593750000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2043-10-20T00:00:00Z",
          "total_amount": "796875000000",
          "applied_amount": "0"
        },
        {
          "end_time": "2047-10-20T00:00:00Z",
          "total_amount": "796875000000",
          "applied_amount": "0"
        }
      ]
</pre>
</td>
<td>
<pre>
假设首块时间为2019-11-01,平均出块时间为5秒,则
第一阶段总块数`19992960`,每块通胀值为`1275448`,即每块产生的QOS约为128(1275448/10000).
第二阶段总块数`25246080`,每块通胀值为`505028`,每块产生的QOS约为51(505028/10000). 
第三阶段总块数`25246080`,每块通胀值为`252514`,每块产生的QOS约为25(252514/10000).
第四阶段总块数`25246080`,每块通胀值为`126158`,每块产生的QOS约为13(126158/10000).
</pre>

</td>
</tr>
<tr>
<td>first_block_time</td>
<td>首块出块时间</td>
<td>0</td>
<td>0</td>
<td>该值由QOS主链第一块的出块时间决定,不可配置</td>
</tr>

<tr>
<td>applied_qos_amount</td>
<td>已流通的QOS总量. 已流通的QOS总量 = 初始账户QOS总量 + 通胀产生的QOS总量</td>
<td>0</td>
<td>-</td>
<td>
主网上线前,以太坊上持有QOS的账户通过操作(如锁币等)转换为QOS公链的初始账户. `已流通的QOS总量`初始值为所有初始账户的QOS总量之和.
</td>
</tr>
</tbody>
<table>


### 分配模块

|参数名称|参数释义|测试网默认值|主网上线设定值|备注|
|---|---|---|---|---|
|proposer_reward_rate|在每块奖励分配中,由块的提议者单独获得的奖励比率. 该奖励将直接进入提议人的待奖励池中, 在到达该提议人的`委托人收益发放高度周期`后,收益将打入提议人账户中.|0.04|0.01| 主网上线设定值表示在第一阶段, 每块的提议者将会额外获得1.3QOS(1275448*0.01/10000)奖励  |
|community_reward_rate|在每块奖励分配中,由社区单独获得的奖励比率. 社区奖励可通过社区治理投票进行管理. |0.01|0.02| 主网上线设定值表示在第一阶段, 社区在每块中将会获得2.6QOS( )奖励. |
|delegator_income_period_height|委托人收益发放高度周期. 该单位表示每隔多少块对委托人进行委托收益发放.|10|一小时|主网上线设定值表示每小时对委托人进行收益发放.  |
|gas_per_unit_cost|gas单位价格,该单位表示消耗1GAS需要花费多少QOS.|10|100| 主网上线设定值表示1GAS=0.000001QOS(1/100/10000).|

#### 消耗GAS操作说明

** <font color='red'>该部分数值在程序中配置,无法进行动态修改</font> ** 

> 对于普通的转账交易,如A转给B100QOS,将花费约18190GAS, 按主网的GAS价格默认值,约为0.018QOS

##### 访问存储消耗GAS:

|操作|操作说明|当前值|主网上线设置值|
|---|---|---|---|
|HasCost|判断存储中是否包含某数据|1000|1000|
|DeleteCost|删除存储中的数据|1000|1000|
|ReadCostFlat|每读取一次存储|1000|1000|
|ReadCostPerByte|读取存储中的数据,按数据大小进行计算,每字节3GAS|3|3|
|WriteCostFlat|每写入一次存储|2000|2000|
|WriteCostPerByte|按写入存储的数据大小进行计算,每字节30GAS|30|30|
|IterNextCostFlat|循环获取数据时,每次迭代需要30GAS|30|30||


##### TX(事务)类型消耗GAS:

** 每进行一次操作,需要花费的GAS **

|TX|命令说明|当前值|主网上线设置值|
|---|---|---|---|
|submit-proposal||0|0|
|deposit||0|0|
|vote||0|0|
|add-guardian||0|0|
|delete-guardian||0|0|
|create-qsc||0|1.8QOS|
|issue-qsc||0|0.18QOS|
|create-approve||0|0|
|increase-approve||0|0|
|decrease-approve||0|0|
|use-approve||0|0|
|cancel-approve||0|0|
|init-qcp||0|1.8QOS|
|create-validator||0|1.8QOS|
|modify-validator||0|0.18QOS|
|revoke-validator||0|18QOS|
|active-validator||0|0|
|delegate||0|0|
|modify-compound||0|0|
|unbond||0|0.18QOS|
|redelegate||0|0|
|transfer||0|0.018QOS|
|invariant-check||10000000|200000QOS||

### 委托模块

|参数名称|参数释义|测试网默认值|主网上线设定值|备注|
|---|---|---|---|---|
|max_validator_cnt|验证者最大数量. 根据验证人绑定的QOS数量进行排名,QOS公链将选取前`max_validator_cnt`数量的验证人作为下一块的验证人集合. 排名在该值之外的验证者会被标示为`INACTIVE`,将无法进行投票、获取收益. QOS白皮书中规定验证者数量为21. |21|21|根据QOS白皮书指定|
|survival_secs|处于`INACTIVE`状态的验证者存活时间. 处于`INACTIVE`状态的验证者在该时间内无有效操作的话会被视为无效验证者,QOS将解除其所有的委托关系. 单位: 秒|600|8小时| 主网上线设定值表示存活时间为8小时|
|unbond_frozen_height|用户进行解绑操作后,解绑的QOS会被冻结一定时间.在该时间之后,解绑的QOS将返还至用户账户中|10|**宜播确定**||
|redelegation_active_height|用户转委托的生效时间. 用户转委托后,转委托的QOS将会被冻结一段时间,在该时间之后,转委托操作生效|10|1天||
|max_evidence_age|双签记录留存时间. 超过该配置时间的双签记录视为已过期的记录,不会对验证人进行惩罚. 单位: 纳秒|1814400000000000|1814400000000000|主网上线设定值1814400000000000 ~= 21天.|
|slash_fraction_double_sign|双签惩罚百分比. 当验证者发生双签时,会对其绑定的TOKEN进行相应百分比的惩罚. |0.05|0.20|主网上线设定值表示对双签的验证者将扣除其20%的绑定的QOS.|
|slash_fraction_downtime|漏块惩罚百分比. 当验证者在投票周期内投票数低于最少投票数时,会对其绑定的TOKEN进行相应百分比的惩罚. |0.0001|0.0001|主网上线设定值表示对不活跃的验证者将扣除其0.1%的绑定的QOS|
|voting_status_len|验证人投票统计周期, 以该高度为周期统计验证者的投票情况,在该周期内,验证人至少要进行`voting_status_least`次投票,否则将会被置为`INACTIVE`状态|10000|10000|主网上线设定值10000约为13个小时,即以13小时为周期对验证者的投票情况进行统计|
|voting_status_least|验证人统计周期内最少投票数,验证人投票周期内,最少要进行投票的次数|500|7000|主网上线设定值表示在13个小时内,验证人至少要在线投票9小时(7000*5s/3600).验证人可在其他时间对系统进行维护,升级等其他操作|
