### ISSUE TITLE
经济模型相关参数确认

### ISSUE THREAD

**Issue by datalj** [QOSGroup/qos#265]

**Comment by TokenxyWZY** [comment]
## 经济模型模块相关参数

### 铸币/挖矿模块

<table>
<tr>
<th>参数名称</th>
<th>参数释义</th>
<th>默认值</th>
<th>主网上线设定值</th>
<th>备注</th>
</tr>
<tbody>
<tr>
<td>inflation_phrases</td>
<td>通胀阶段配置</td>
<td>
<pre lang =“json”>
[
        {  
           "end_time": "2023-01-01T00:00:00Z",
           "total_amount": "2500000000000",
           "applied_amount": "0"
          }, 
          {  
           "end_time": "2027-01-01T00:00:00Z",
           "total_amount": "12750000000000",
            "applied_amount": "0"
          }, 
          {  
          "end_time": "2031-01-01T00:00:00Z",
          "total_amount": "6375000000000",
          "applied_amount": "0"
          }, 
          {  
            "end_time": "2035-01-01T00:00:00Z",
            "total_amount": "3185000000000",
            "applied_amount": "0"
          }  
 ] 
</pre>
</td>
<td>?</td>
<td>根据OQS白皮书规则指定.
<pre>
假设首块时间为2019-11-01,出块平均时间为5秒,
则第一阶段每块通胀值为`125000`,即每块产生的QOS约为13.
第二阶段每块通胀值为`505000`,每块产生的QOS约为50. 
第三阶段每块通胀值为`252500`,每块产生的QOS约为25.
第四阶段每块通胀值为`126100`,每块产生的QOS约为13.
</pre>

</td>
</tr>
<tr>
<td>first_block_time</td>
<td>首块出块时间</td>
<td>0</td>
<td>0</td>
<td>该值为首块的出块时间,由QOS主链第一块的出块时间决定,不可配置</td>
</tr>

<tr>
<td>applied_qos_amount</td>
<td>已流通的QOS总量</td>
<td>0</td>
<td>-</td>
<td>主网上线时,以太坊上持有QOS的账户通过锁币操作成为QOS主链的初始账户. `已流通的QOS总量`初始值为所有初始账户的QOS总量之和</td>
</tr>
</tbody>
<table>



### 分配模块

|参数名称|参数释义|默认值|主网上线设定值|备注|
|---|---|---|---|---|
|proposer_reward_rate|在每块奖励分配中,由提议者单独获得的奖励比率|0.04|?|每块的奖励由每块交易的GAS费和通胀两部分组成.|
|community_reward_rate|在每块奖励分配中,由社区单独获得的奖励比率|0.01|?||
|delegator_income_period_height|委托人收益发放高度周期|10|?|该单位表示每隔多少时间对委托人进行委托收益发放,默认值10表示大约每50秒进行一次分配. 收益初始高度为首次委托验证者时的高度|
|gas_per_unit_cost|gas单位价格|10|?|该单位表示消耗1单位GAS需要花费多少QOS|

### 委托模块

|参数名称|参数释义|默认值|主网上线设定值|备注|
|---|---|---|---|---|
|max_validator_cnt|验证者最大数量|10|?|该值表示公链内拥有投票权的验证者最大数量.验证者根据其绑定QOS数量进行排名,排名在该值之外的验证者会被标示为`INACTIVE`,将无法进行投票、获取收益.|
|survival_secs|处于`INACTIVE`状态的验证者存活时间. 单位: 秒|600|?|处于`INACTIVE`状态的验证者在该时间内无操作的话会被视为无效验证者,QOS将解除其所有的委托关系. 默认值600表示存活时间为10分钟,约为120块|
|unbond_return_height|用户通过解绑操作后,解绑的QOS会被冻结一定时间.在该时间后,解绑的QOS将返至用户账户中|10|?|默认值10块表示冻结时间为50秒|
|redelegation_height|用户重委托时生效时间|10|||
|max_evidence_age|双签记录留存时间. 单位: 纳秒|600000000||600000000 ~= 0.6秒, 超过该配置时间的双签记录视为已过期的记录,不会对验证人进行惩罚|
|slash_fraction_double_sign||0.2|||
|slash_fraction_downtime||0.1|||
|voting_status_len|验证人投票周期高度|100||验证人投票统计配置. 在`voting_status_len`投票周期高度内,验证人至少要进行`voting_status_least`次投票,否则将会被置位`INACTIVE`状态|
|voting_status_least|验证人投票周期高度内,最少要进行投票的次数|50||验证人投票统计配置.|

**Comment by TokenxyWZY** [comment]
第一版参数已确定,待验证

**Comment by TokenxyWZY** [comment]
see #263
