### ISSUE TITLE
提供QOS验证节点部署方案

### ISSUE THREAD

**Issue by datalj** [QOSGroup/qos#267]

**Comment by TokenxyWZY** [comment]
# QOS节点部署方案

## 参数说明

* config.toml

|参数|取值|说明|
|--|--|--|
|p2p/pex|bool|在node中是否开启`peer exchange reactor (gossip protocol)`. 若该参数为`false`, 则节点只能连接`persistent_peers`中配置的节点|
|p2p/persistent_peers|node_id@ip:port|node节点将会一直连接的节点|
|p2p/private_peer_ids|node_id|在此配置中的nodeid不会被gossip出去|
|p2p/addr_book_strict|boolean|node节点部署在公网时,设为true,否则设为false|
|p2p/seed_mode|boolean|node是否为seed 模式||


## 部署方案

![部署方案](https://github.com/TokenxyWZY/static/blob/master/%E8%8A%82%E7%82%B9%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88.png)


### 方案: 单验证节点

#### 配置参数

```
seeds = "1233b1c5bad7561d7c5a28b4a2149760a8b673d2@47.103.79.28:26656" #QOS提供的seed节点
pex = true
```

#### 方案优点

1. 部署简单

#### 方案缺点

1. 验证节点IP暴露在公网上,容易受到DDoS攻击
2. 验证节点只能通过防火墙来保护自己的安全

### 方案: 哨兵-验证节点

#### 配置参数

|节点类型|节点nodeID|节点公网IP|节点内网IP|
|--|--|--|
|验证节点|val-node-id|-|val-inter-ip|
|哨兵节点A|sentryA-node-id|sentryA-pub-ip|sentryA-inter-ip|
|哨兵节点B|sentryB-node-id|sentryB-pub-ip|sentryB-inter-ip|

验证节点配置:

```
pex=false
persistent_peers="sentryA-node-id@sentryA-inter-ip:26656;sentryB-node-id@sentryB-inter-ip:26656"
addr_book_strict=false
```

哨兵节点A配置:

```
pex=true
seeds = "1233b1c5bad7561d7c5a28b4a2149760a8b673d2@47.103.79.28:26656" #QOS提供的seed节点
persistent_peers="val-node-id@val-inter-ip:26656"
private_peer_ids="val-node-id"
addr_book_strict=false
```

哨兵节点B配置:

```
pex=true
seeds = "1233b1c5bad7561d7c5a28b4a2149760a8b673d2@47.103.79.28:26656" #QOS提供的seed节点
persistent_peers="val-node-id@val-inter-ip:26656"
private_peer_ids="val-node-id"
addr_book_strict=false
```

#### 方案优点

1.  可以有效减少DDoS攻击
2.  验证节点通过哨兵节点提供服务,并不暴露自己的IP地址

#### 方案缺点

1. 所有哨兵节点均受到DDoS攻击时,将会导致验证节点无法正常进行投票
2. 哨兵节点无法动态扩容

### 方案: 哨兵-中继-验证节点

* 配置参数

|节点类型|节点nodeID|节点公网IP|节点内网IP|节点VPN IP|
|--|--|--|--|
|验证节点A|valA-node-id|-|valA-inter-ip|--|
|中继节点A|relayA-node-id|-|relayA-inter-ip|relayA-vpn-ip|
|哨兵节点AA|sentryAA-node-id|sentryAA-pub-ip|sentryAA-inter-ip|--|
|哨兵节点AB|sentryAB-node-id|sentryAB-pub-ip|sentryAB-inter-ip|--|
|验证节点B|valB-node-id|-|valB-inter-ip|--|
|中继节点B|relayB-node-id|-|relayB-inter-ip|relayB-vpn-ip|
|哨兵节点BA|sentryBA-node-id|sentryBA-pub-ip|sentryBA-inter-ip|--|
|哨兵节点BB|sentryBB-node-id|sentryBB-pub-ip|sentryBB-inter-ip|--|

验证节点A配置:

```
pex=false
persistent_peers="relayA-node-id@relayA-inter-ip:26656"
addr_book_strict=false
```

哨兵节点AA配置:

```
pex=true
seeds = "1233b1c5bad7561d7c5a28b4a2149760a8b673d2@47.103.79.28:26656" #QOS提供的seed节点
persistent_peers="relayA-node-id@relayA-inter-ip:26656"
private_peer_ids="relayA-node-id"
addr_book_strict=false
```

哨兵节点AB配置:

```
pex=true
seeds = "1233b1c5bad7561d7c5a28b4a2149760a8b673d2@47.103.79.28:26656" #QOS提供的seed节点
persistent_peers="relayA-node-id@relayA-inter-ip:26656"
private_peer_ids="relayA-node-id"
addr_book_strict=false
```

中继节点A配置:

```
pex=true
persistent_peers="sentryAA-node-id@sentryAA-inter-ip:26656;sentryAB-node-id@sentryAB-inter-ip:26656;relayB-node-id@relayB-vpn-ip:26656"
private_peer_ids="sentryAA-node-id;sentryAB-node-id;relayB-node-id"
addr_book_strict=false
```

> 验证节点B配置与验证节点A配置类似,区别在中继节点B配置时其连接中继节点A的VPN IP


#### 方案优点

1. 哨兵节点受到DDoS攻击时,验证节点仍可以通过其他中继节点进行投票

#### 方案缺点

1. 配置过多,需要专业运维人员进行配置


## 验证节点私钥安全方案

验证节点私钥被其他人恶意获取后,则验证节点会被恶意双签,导致受到严重的`slash`惩罚. 因此保护好验证节点的私钥至关重要.

私钥安全方案建议:

1.  存储私钥的机器需要有严格的登录限制,做好监控工作
2.  可以通过开启私钥签名服务将私钥文件与验证节点物理隔离

**Comment by TokenxyWZY** [comment]
![节点部署方案](https://user-images.githubusercontent.com/43430532/64426942-81c70180-d0e2-11e9-94c4-723b65d6fad9.png)
