### ISSUE TITLE
gas cost

### ISSUE THREAD

**Issue by imuge** [QOSGroup/qos#283]
Set a suitable value before launch

Store:
- HasCost
- DeleteCost
- ReadCostFlat
- ReadCostPerByte
- WriteCostFlat
- WriteCostPerByte
- IterNextCostFlat

Txs:
- submit-proposal  Submit proposal
- deposit          deposit
- vote             vote

- add-guardian     Add guardian
- delete-guardian  Delete guardian

- create-qsc       create qsc
- issue-qsc        issue qsc

- create-approve   Create approve
- increase-approve Increase approve
- decrease-approve Decrease approve
- use-approve      Use approve
- cancel-approve   Cancel approve

- init-qcp         init qcp

- create-validator create new validator initialized with a self-delegation to it
- modify-validator modify an existing validator account
- revoke-validator Revoke validator
- active-validator Active validator
- delegate         delegate QOS to a validator
- modify-compound  modify compound info in a delegation
- unbond           unbond QOS from a validator
- redelegate       redelegate QOS from a validator to another

- transfer         Transfer QOS and QSCs
- invariant-check  submit invariant checking tx to proof an invariant broken and halt the chain

**Comment by TokenxyWZY** [comment]
##### 访问存储消耗GAS:

|操作|操作说明|当前值|主网上线设置值|
|---|---|---|---|
|HasCost|判断存储中是否包含某数据|1000|1000|
|DeleteCost|删除存储中的数据|1000|1000|
|ReadCostFlat|每读取一次存储|1000|1000|
|ReadCostPerByte|读取存储中的数据,按数据大小进行计算,每字节3GAS|3|3|
|WriteCostFlat|每写入一次存储|2000|2000|
|WriteCostPerByte|按写入存储的数据大小进行计算,每字节30GAS|30|30|
|IterNextCostFlat|循环获取数据时,每次迭代需要30GAS|30|30||


##### TX(事务)类型消耗GAS:

** 每进行一次操作,需要花费的GAS **

|TX|命令说明|当前值|主网上线设置值|
|---|---|---|---|
|submit-proposal||0|0|
|deposit||0|0|
|vote||0|0|
|add-guardian||0|0|
|delete-guardian||0|0|
|create-qsc||0|1.8QOS|
|issue-qsc||0|0.18QOS|
|create-approve||0|0|
|increase-approve||0|0|
|decrease-approve||0|0|
|use-approve||0|0|
|cancel-approve||0|0|
|init-qcp||0|1.8QOS|
|create-validator||0|1.8QOS|
|modify-validator||0|0.18QOS|
|revoke-validator||0|18QOS|
|active-validator||0|0|
|delegate||0|0|
|modify-compound||0|0|
|unbond||0|0.18QOS|
|redelegate||0|0|
|transfer||0|0.018QOS|
|invariant-check||10000000|200000QOS||
