### ISSUE TITLE
创建验证人节点时令绑定的Tokens为负值，未进行入参检查，导致QOS网络崩溃

### ISSUE THREAD

**Issue by WZJ-Study** [QOSGroup/qos#295]
![image](https://user-images.githubusercontent.com/25134023/63326363-a7bc7a00-c35e-11e9-8a3f-4d2d8283e29c.png)

### 这是发起交易的节点qosd:
![image](https://user-images.githubusercontent.com/25134023/63326411-c458b200-c35e-11e9-979c-f9d43fde77f2.png)

### 这是peer节点的qosd:
![image](https://user-images.githubusercontent.com/25134023/63326444-da667280-c35e-11e9-8332-389f0a5bf659.png)

### 可以看到peer节点的qosd在ApplyBlock时直接崩溃了，报错显示错误的validator创建成功了，导致voting power成为负数。

**Comment by TokenxyWZY** [comment]
fix #311
