### ISSUE TITLE
发起类型为`TaxUsage`的提案时，令提取比例(percent)为零或负值，错误提示有问题

### ISSUE THREAD

**Issue by WZJ-Study** [QOSGroup/qos#296]
![image](https://user-images.githubusercontent.com/25134023/63401024-739d9380-c408-11e9-9c47-e6025d8e9c09.png)
### 如上所示，发起类型为`TaxUsage`的提案时，令提取比例(percent)为零或负值，错误提示为“deposit must be positive”，但这里deposit的确为正数(60000), 错误提示应该为”percent必须为正数“

**Comment by TokenxyWZY** [comment]
fix #330
