### ISSUE TITLE
tally info not updated in proposals query information

### ISSUE THREAD

**Issue by MattWangming** [QOSGroup/qos#334]
Hi, there is some confusion on the `tally` information in `proposals` and `tally` query operation results:
On `query proposal`, it is print out with:
```
{"proposal_content":{"type":"gov/TextProposal","value":
...
"final_tally_result":{"yes":"0","abstain":"0","no":"0","no_with_veto":"0"}
...
```

On `query tally`, it is print out with:
```
./qoscli query tally 2 --node "tcp://192.168.1.221:26657"
{"yes":"100000000","abstain":"0","no":"0","no_with_veto":"0"}
```

Why this info on `tally` different in the 2 query operations?

**Comment by imuge** [comment]
`final_tally_result` in `query proposal` refers to the final vote result.
`query tally` refers to the real-time voting.

**Comment by imuge** [comment]
@MattWangming
