### ISSUE TITLE
向inactive状态的验证人redelegate失败

### ISSUE THREAD

**Issue by WZJ-Study** [QOSGroup/qos#340]
================================================================

> # 重新委托: 委托人charles, 原验证人node, 新验证人alice, 转移所有, 启用复投, 测试由活跃验证人节点node向关停验证人节点alice转移委托

================================================================

== Command [ No.48 ]

> qoscli tx redelegate --from-validator $(cat v_node.temp) --to-validator $(cat v_alice.temp) --delegator charles --all --compound --indent <== 12345678

== 交易之前 ==

账户余额状态
| key                                           | qos                  | star                 |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |             10000000 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |              4978683 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |              5994749 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |       48999955000000 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |             10000000 |                    0 |

账户余额变动情况
| key                                           | Delta qos            | Delta star           |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |                    0 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |                    0 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |                    0 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |                    0 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |                    0 |                    0 |

社区费池情况
| community_fee        | Delta community_fee  |
| -------------------: | -------------------: |
|             90236711 |                    0 |

== 执行交易 ==

~/qos/bin/qoscli tx redelegate --from-validator $(cat v_node.temp) --to-validator $(cat v_alice.temp) --delegator charles --all --compound --indent 

== 原始交易结果 ==

--------------------------------
Expect命令:
expect 2>&1 /home/admin/qos/expect/run_cmd_via_ssh.expect 192.168.2.129 admin admin '~/qos/bin/qoscli tx redelegate --from-validator $(cat v_node.temp) --to-validator $(cat v_alice.temp) --delegator charles --all --compound --indent' 12345678
命令执行结果:
{
  "check_tx": {
    "code": 1,
    "log": "{\"codespace\":\"sdk\",\"code\":1,\"message\":\"TxStd's ITx ValidateData error:  Validator status not match. except: 0, actual:1.\"}",
    "gasWanted": "9223372036854775807",
    "gasUsed": "3587",
    "events": []
  },
  "deliver_tx": {},
  "hash": "2C6E0F428917B0E899B1F5EA72609EA71A873C7A2C04B422B9D76E41A08F9D27",
  "height": "0"
}
ERROR: {"codespace":"sdk","code":1,"message":"TxStd's ITx ValidateData error:  Validator status not match. except: 0, actual:1."}
命令执行耗时: 1714 ms
结果处理耗时: 27 ms
--------------------------------

== 提取交易哈希 ==

2C6E0F428917B0E899B1F5EA72609EA71A873C7A2C04B422B9D76E41A08F9D27

== 查询链上交易记录 ==

ERROR: Tx: response error: RPC error -32603 - Internal error: Tx (2C6E0F428917B0E899B1F5EA72609EA71A873C7A2C04B422B9D76E41A08F9D27) not found

错误: 未查询到链上交易记录

== 交易失败 ==

**Comment by imuge** [comment]
转委托生效时，如果目标验证节点不存在会直接将绑定token返还至委托账户
