### ISSUE TITLE
委托人从验证人处unbond all之后，unbond金额到账，委托信息未被删除

### ISSUE THREAD

**Issue by WZJ-Study** [QOSGroup/qos#341]
================================================================

> # 解除绑定: 委托人charles, 验证人node, 再解绑剩余所有, 预期交易成功

================================================================

== Command [ No.18 ]

> qoscli tx unbond --validator $(cat v_node.temp) --delegator charles --all --indent <== 12345678

== 交易之前 ==

账户余额状态
| key                                           | qos                  | star                 |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |             10000000 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |              4997703 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |              7498394 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |       48999955000000 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |             10000000 |                    0 |

账户余额变动情况
| key                                           | Delta qos            | Delta star           |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |                    0 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |                    0 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |              2500000 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |                    0 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |                    0 |                    0 |

社区费池情况
| community_fee        | Delta community_fee  |
| -------------------: | -------------------: |
|             46765512 |              3118233 |

== 执行交易 ==

~/qos/bin/qoscli tx unbond --validator $(cat v_node.temp) --delegator charles --all --indent 

== 原始交易结果 ==

--------------------------------
Expect命令:
expect 2>&1 /home/admin/qos/expect/run_cmd_via_ssh.expect 192.168.2.129 admin admin '~/qos/bin/qoscli tx unbond --validator $(cat v_node.temp) --delegator charles --all --indent' 12345678
命令执行结果:
{
  "check_tx": {
    "gasWanted": "9223372036854775807",
    "gasUsed": "26306",
    "events": []
  },
  "deliver_tx": {
    "gasWanted": "9223372036854775807",
    "gasUsed": "79600",
    "events": [
      {
        "type": "unbond-delegation",
        "attributes": [
          {
            "key": "dmFsaWRhdG9y",
            "value": "cW9zdmFsMXFnd2dtcHNyZDZhbmozcWp2anNxenRqM3h0OXYyNGM0ODV4N2tr"
          },
          {
            "key": "ZGVsZWdhdG9y",
            "value": "cW9zYWNjMWYzN2p2bmVocmZrcHd6cXRxdHU1cTlqeDU3MDM0Z3Z2dHY1YTM2"
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "bW9kdWxl",
            "value": "c3Rha2U="
          },
          {
            "key": "Z2FzLnBheWVy",
            "value": "cW9zYWNjMWYzN2p2bmVocmZrcHd6cXRxdHU1cTlqeDU3MDM0Z3Z2dHY1YTM2"
          }
        ]
      }
    ]
  },
  "hash": "68B1524ECD632D7DDB8B32B5A2D0EE5C51336F69C8DEFC29A3EF8C1138597BEA",
  "height": "20"
}
命令执行耗时: 6223 ms
结果处理耗时: 21 ms
--------------------------------

== 提取交易哈希 ==

68B1524ECD632D7DDB8B32B5A2D0EE5C51336F69C8DEFC29A3EF8C1138597BEA

== 查询链上交易记录 ==

{
  "height": "20",
  "txhash": "68B1524ECD632D7DDB8B32B5A2D0EE5C51336F69C8DEFC29A3EF8C1138597BEA",
  "gas_wanted": "9223372036854775807",
  "gas_used": "79600",
  "events": [
    {
      "type": "message",
      "attributes": [
        {
          "key": "module",
          "value": "stake"
        },
        {
          "key": "gas.payer",
          "value": "qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36"
        }
      ]
    },
    {
      "type": "unbond-delegation",
      "attributes": [
        {
          "key": "validator",
          "value": "qosval1qgwgmpsrd6anj3qjvjsqztj3xt9v24c485x7kk"
        },
        {
          "key": "delegator",
          "value": "qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36"
        }
      ]
    }
  ],
  "tx": {
    "type": "qbase/txs/stdtx",
    "value": {
      "itx": [
        {
          "type": "stake/txs/TxUnbondDelegation",
          "value": {
            "Delegator": "qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36",
            "ValidatorAddr": "qosval1qgwgmpsrd6anj3qjvjsqztj3xt9v24c485x7kk",
            "UnbondAmount": "0",
            "IsUnbondAll": true
          }
        }
      ],
      "sigature": [
        {
          "pubkey": {
            "type": "tendermint/PubKeyEd25519",
            "value": "UinjHf4xnFzTi0tdq+8ooehKg70WCpdXu48j37kIc8M="
          },
          "signature": "H2v6I/40x3sa3vefFNSgYX0Tqf6mX8cnTRbVQF2NGj0Z2BUNu3EmzyFSrfgJtEId/romYlHJKAc08nl7a4nADw==",
          "nonce": "5"
        }
      ],
      "chainid": "test-chain",
      "maxgas": "9223372036854775807"
    }
  },
  "timestamp": "2019-09-11T09:00:38Z"
}

== 交易成功 ==

== 交易生效过程 ==

到达新块: [20] ==> [21]

账户余额状态
| key                                           | qos                  | star                 |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |             10000000 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |              4997703 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |              7497598 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |       48999955000000 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |             10000000 |                    0 |

账户余额变动情况
| key                                           | Delta qos            | Delta star           |
| --------------------------------------------: | -------------------: | -------------------: |
| qosacc15fc26swvguzy9wksha9506smj2gne5r3jd978f |                    0 |                    0 |
| qosacc1dkcds02rw2nwme34wvq4uym83nh8rz05h6x7nr |                    0 |                    0 |
| qosacc1eqqnaps04l6ht9xahtrfgg59ksllcq9q85vje2 |                    0 |                    0 |
| qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36 |                 -796 |                    0 |
| qosacc1n4sganm7v445h0dlqnlcq8hp8xgenl2sszd5pm |                    0 |                    0 |
| qosacc1qgwgmpsrd6anj3qjvjsqztj3xt9v24c4lygasm |                    0 |                    0 |
| qosacc1xhlsragqdn0cp7a2dcf45fy8j0nej9jlrv753m |                    0 |                    0 |

社区费池情况
| community_fee        | Delta community_fee  |
| -------------------: | -------------------: |
|             51051993 |              4286481 |

================================================================

> # 等待10秒

================================================================

== Command [ No.19 ]

> sleep 10

--------------------------------
Expect命令:
expect 2>&1 /home/admin/qos/expect/run_cmd_via_ssh.expect 192.168.2.129 admin admin 'sleep 10' 
命令执行结果:

命令执行耗时: 10697 ms
结果处理耗时: 32 ms
--------------------------------

================================================================

> # 查询委托: 委托人charles, 验证人node, 检查完全解绑后的委托情况

================================================================

== Command [ No.20 ]

> qoscli query delegation --validator $(cat v_node.temp) --delegator charles --indent

--------------------------------
Expect命令:
expect 2>&1 /home/admin/qos/expect/run_cmd_via_ssh.expect 192.168.2.129 admin admin '~/qos/bin/qoscli query delegation --validator $(cat v_node.temp) --delegator charles --indent' 
命令执行结果:
{
  "delegator_address": "qosacc1f37jvnehrfkpwzqtqtu5q9jx57034gvvtv5a36",
  "validator_address": "qosval1qgwgmpsrd6anj3qjvjsqztj3xt9v24c485x7kk",
  "validator_cons_pub_key": "qosconspub1zcjduepquvx850nw5y4q8v373kdclak7cml0zw9lx2zwwn8d69ylvhfh54zqt2kt5c",
  "delegate_amount": "0",
  "is_compound": false
}
命令执行耗时: 1874 ms
结果处理耗时: 12 ms
--------------------------------

**Comment by wangkuanzzu** [comment]
在等待一个收益发放周期后 "delegator_income_period_height": "720",，绑定tokens为0的委托会被删除。
