### ISSUE TITLE
发币报错了

### ISSUE THREAD

**Issue by tedyyan** [QOSGroup/qos#39]
[qstars@testnet006 cmd]$ ./qosappcli -m=txissue -qscname=QSC -nonce=1 -qoschainid=qos -maxgas=100 -amount=20000  
tx result:  &{65537  {"codespace":1,"code":1,"abci_code":65537,"message":"chainId not match. expect: qosrace , actual: qos"} 58BD78C398B2EFCC5758E1995098BC58B636C9BB}

**Comment by MicroWave001** [comment]
命令行参数 qoschainid 为公链chainid的名字，需和qosd init时指定的chainid名字匹配
